[package]
name = "subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.3"
zenoh = "0.11.0"
tokio =  { version = "1.36.0", features = ["macros", "rt-multi-thread", "full"] }
tokio-stream = "0.1.15"
